version: '3'
services:
  nginx:
    image: 61231/4dvop-app:nginx-4dvop
    ports:
      - "8080:8080"
  haproxy:
    image: 61231/4dvop-app:haproxy-4dvop
    ports:
      - "80:80"
    depends_on:
      - nginx

